import '@watheia/ui-theme/styles.css';

export const metadata = {
  title: 'Welcome to home',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/firacode@6.2.0/distr/fira_code.css"
        ></link>
      </head>
      <body>{children}</body>
    </html>
  );
}
